version: '3.1'

services:

  database:
    image: mariadb:latest
    restart: always
    container_name: base-to-phpmyadmin
    ports: ["3309:3306"]
    environment:
      - MYSQL_DATABASE=base
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - base-network
    volumes:
      - base-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - base-network


    









volumes:
  base-volume:

networks:
      base-network:
       driver: bridge